/**
 * Server-only lookup for DB-derived content translations (package fields,
 * component titles, city/state names, hotel names) shipped as
 * data/content/{hi,ta}.json and generated by scripts/content-build.mjs.
 *
 * The catalog DB stays the read-only source of truth for the English values;
 * this module supplies the localised overlay and falls back to the original
 * English string when a key or language is missing. Use from server
 * components / route handlers only — it reads the filesystem.
 */
import fs from "node:fs";
import path from "node:path";

const cache = new Map<string, Record<string, string>>();

export function contentDict(lang: string | null | undefined): Record<string, string> {
  const base = (lang ?? "en").split("-")[0]!.toLowerCase();
  if (base === "en") return {};
  const cached = cache.get(base);
  if (cached) return cached;
  const file = path.join(process.cwd(), "data", "content", `${base}.json`);
  const dict: Record<string, string> = {};
  if (fs.existsSync(file)) {
    try {
      Object.assign(dict, JSON.parse(fs.readFileSync(file, "utf-8")) as Record<string, string>);
    } catch {
      // fall through to empty dict — English fallback applies
    }
  }
  cache.set(base, dict);
  return dict;
}

export function localizeContent(lang: string | null | undefined, key: string, fallback: string): string {
  return contentDict(lang)[key] ?? fallback;
}